### ISSUE TITLE
Crash with newest Terrestria

### ISSUE THREAD

**Issue by Blatts12** [TerraformersMC/Traverse#29]
Terrestria 2.0.2
Traverse 2.2.11
https://pastebin.com/8SCDc169

**Comment by NeusFear** [comment]
Something is jij an old version of Terraform, I'm not sure why it's not taking the newest version

**Comment by NeusFear** [comment]
This is an issue with Lakeside, report this on their github and link this issue to them. Lakeside needs to update Terraform to one of the 2.x verions

**Comment by coderbot16** [comment]
I think it's Lakeside that is indirectly triggering the crash by bundling an old Terraform. But Traverse and Terrestria should be specifying their minimum required Terraform version, because otherwise Fabric will load the "most compatible" version based on the mod metadata - which is not necessarily the latest.

**Comment by NeusFear** [comment]
Turns out we need to bump Cinderscapes too.

**Comment by coderbot16** [comment]
This is also a Traverse and Terrestria issue. They do not properly constrain their Terraform dependency in the mod json.
